[database]
file = "./vzdv_data.sqlite"
resource_category_ordering = []

[staff]
email_domain = ""
overrides = []

[vatsim]
vatusa_api_key = ""
oauth_url_base = ""
oauth_client_id = ""
oauth_client_secret = ""
oauth_client_callback_url = ""

[training]
certifications = []

[airports]
all = []
weather_for = []

[stats]
position_prefixes = []
position_suffixes = []

[discord]
join_link = ""
api_key = ""

[discord.webhooks]
staffing_request = ""
feedback = ""
