[database]
file = "./vzdv_data.sqlite"

[staff]
email_domain = ""
overrides = []

[vatsim]
oauth_client_id = ""
oauth_client_secret = ""
oauth_client_callback_url = ""
vatusa_facility_code = ""

[training]
certifications = []

[airports]
all = []
weather_for = []

[stats]
position_prefixes = []
position_suffixes = []

[webhooks]
staffing_request = ""
feedback = ""
