[database]
file = "./vzdv_data.sqlite"

[training]
certifications = []

[airports]
all = []
weather_for = []

[stats]
position_prefixes = []
position_suffixes = []

[webhooks]
staffing_request = ""
feedback = ""
