[database]
file = "./vzdv_data.sqlite"
resource_category_ordering = []

[staff]
email_domain = ""
overrides = []

[vatsim]
vatusa_api_key = ""
oauth_url_base = ""
oauth_client_id = ""
oauth_client_secret = ""
oauth_client_callback_url = ""

[training]
certifications = []

[airports]
all = []
weather_for = []

[stats]
position_prefixes = []
position_suffixes = []

[discord]
join_link = ""
bot_token = ""
guild_id = 0
online_channel = 0
# online_message = 0

[discord.webhooks]
staffing_request = ""
feedback = ""
new_visitor_app = ""

[discord.roles]
# role
guest = ""
controller_otm = ""
visiting_controller = ""
neighboring_controller = ""

# staff
sr_staff = ""
jr_staff = ""
vatusa_vatgov_staff = ""

# staff teams
training_staff = ""
event_team = ""
fe_team = ""
web_team = ""
ace_team = ""

# ratings
administrator = ""
supervisor = ""
instructor_3 = ""
instructor_1 = ""
controller_3 = ""
controller_1 = ""
student_3 = ""
student_2 = ""
student_1 = ""
observer = ""

[email]
host = ""
port = 0
user = ""
password = ""
from = ""
reply_to = ""

[email.visitor_accepted_template]
subject = ""
body = ""

[email.visitor_denied_template]
subject = ""
body = ""

[email.visitor_removed_template]
subject = ""
body = ""

