name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "7ee02414-911d-42f1-8867-383492c41111"
        save-if: ${{ github.ref == 'refs/heads/master' }}
    - name: Install clippy
      run: rustup component add clippy
    - name: Run tests
      run: cargo test --verbose --all
    - name: Run clippy
      run: cargo clippy
